---
bash_packages:
  - bash
  - exa
  - fzf
  - jq
  - just
  - pass
  - starship
  - the_silver_searcher
  - tldr
  - unzip
  - vim
  - xclip
bash_config_files:
  - ~/.bashrc
  - ~/.config/starship.toml
