---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ bash_packages[ansible_facts.os_family] }}"
    state: latest

- name: Create .local/bin folder
  ansible.builtin.file:
    path: "~/.local/bin"
    state: directory
    mode: "0755"

- name: Install starship
  when: ansible_facts.os_family == "Debian"
  block:
    - name: Check if starship is already installed
      ansible.builtin.command: which starship
      failed_when: false
      changed_when: false
      check_mode: false
      register: bash_which_starship

    - name: Download starship install script
      ansible.builtin.get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/install-starship.sh
        mode: "0775"
      when: bash_which_starship.rc == 1

    - name: Run starship install script
      ansible.builtin.command: /tmp/install-starship.sh --force --bin-dir ~/.local/bin  # yamllint disable-line rule:line-length
      changed_when: true
      when: bash_which_starship.rc == 1

    - name: Download bitwarden-cli
      ansible.builtin.unarchive:
        src: https://vault.bitwarden.com/download/?app=cli&platform=linux
        dest: "~/.local/bin"
        mode: "0755"
        remote_src: true

    - name: Check if just is already installed
      ansible.builtin.command: which just
      failed_when: false
      changed_when: false
      check_mode: false
      register: bash_which_just

    - name: Download just install script
      ansible.builtin.get_url:
        url: https://just.systems/install.sh
        dest: /tmp/install-just.sh
        mode: "0775"
      when: bash_which_just.rc == 1

    - name: Run just install script
      ansible.builtin.command: /tmp/install-just.sh --to ~/.local/bin
      changed_when: true
      when: bash_which_just.rc == 1

- name: Link config files
  ansible.builtin.include_role:
    name: link_config
  vars:
    link_config_files: "{{ bash_config_files }}"
    link_config_file_force: true
