---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ bash_packages[ansible_facts.os_family] }}"
    state: latest
  when: can_become

- name: Create .local/bin folder
  ansible.builtin.file:
    path: "~/.local/bin"
    state: directory
    mode: "0755"

- name: Install starship
  when: ansible_facts.os_family == "Debian"
  block:
    - name: Check if starship is already installed
      ansible.builtin.command: which starship
      failed_when: false
      changed_when: false
      check_mode: false
      register: bash_which_starship

    - name: Download starship install script
      ansible.builtin.get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/install-starship.sh
        mode: "0775"
      when: bash_which_starship.rc == 1

    - name: Run starship install script
      ansible.builtin.command: /tmp/install-starship.sh --force --bin-dir ~/.local/bin  # yamllint disable-line rule:line-length
      changed_when: true
      when: bash_which_starship.rc == 1

    - name: Download bitwarden-cli
      ansible.builtin.unarchive:
        src: https://vault.bitwarden.com/download/?app=cli&platform=linux
        dest: "~/.local/bin"
        mode: "0755"
        remote_src: true

    - name: Check if just is already installed
      ansible.builtin.command: which just
      failed_when: false
      changed_when: false
      check_mode: false
      register: bash_which_just

    - name: Download just install script
      ansible.builtin.get_url:
        url: https://just.systems/install.sh
        dest: /tmp/install-just.sh
        mode: "0775"
      when: bash_which_just.rc == 1

    - name: Run just install script
      ansible.builtin.command: /tmp/install-just.sh --to ~/.local/bin
      changed_when: true
      when: bash_which_just.rc == 1

- name: Build dua
  when: ansible_facts.os_family == "Debian" and ansible_facts.virtualization_type != "docker"  # yamllint disable-line rule:line-length
  block:
    - name: Create temporary directory
      ansible.builtin.file:
        path: /tmp/docker-rust
        state: directory
        mode: "0755"

    - name: Build inside docker container
      community.general.docker_container:
        name: dua_installer
        image: rust
        command: cargo install dua-cli --target-dir /tmp
        cleanup: true
        detach: false
        volumes:
          - /tmp/docker-rust/:/tmp/release

    - name: Copy binary to ~/.local/bin
      ansible.builtin.copy:
        src: /tmp/docker-rust/dua
        dest: ~/.local/bin/
        remote_src: true
        mode: "0755"

- name: Build zellij
  when: ansible_facts.os_family == "Debian" and ansible_facts.virtualization_type != "docker"  # yamllint disable-line rule:line-length
  block:
    - name: Create temporary directory
      ansible.builtin.file:
        path: /tmp/docker-rust
        state: directory
        mode: "0755"

    - name: Build inside docker container
      community.general.docker_container:
        name: zellij_installer
        image: rust
        command: cargo install zellij --target-dir /tmp
        cleanup: true
        detach: false
        volumes:
          - /tmp/docker-rust/:/tmp/release

    - name: Copy binary to ~/.local/bin
      ansible.builtin.copy:
        src: /tmp/docker-rust/zellij
        dest: ~/.local/bin/
        remote_src: true
        mode: "0755"

- name: Add config
  ansible.builtin.include_role:
    name: add_config
  vars:
    add_config_files: "{{ bash_config_files }}"
    add_config_file_force: true
