---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ bash_packages[ansible_facts.os_family] }}"
    state: latest

- name: Link config files
  ansible.builtin.include_role:
    name: link_config
  vars:
    link_config_files: "{{ bash_config_files }}"
    link_config_file_force: true
