---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ mpv_packages }}"
    state: latest

- name: Add config
  ansible.builtin.include_role:
    name: add_config
  vars:
    add_config_files: "{{ mpv_config_files }}"
