---
- hosts: localhost
  connection: local
  become: true
  vars_files: vars.yaml

  roles:
    - role: base
    - role: alacritty
    - role: starship
    - role: git
    - role: i3
    - role: rofi
    - role: emacs

  tasks:
    - name: Install package
      community.general.pacman:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"

    - name: Enable and start service
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop: "{{ services }}"

    - name: Use lightdm slick greeter
      ansible.builtin.lineinfile:
        path: /etc/lightdm/lightdm.conf
        regexp: "^[#]?greeter-session="
        line: "greeter-session=lightdm-slick-greeter"
