---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Sync and refresh
      community.general.pacman:
        update_cache: true

  roles:
    - role: bash
    - role: alacritty
    - role: starship
    - role: git
    - role: i3
    - role: lightdm
    - role: dunst
    - role: volumeicon
    - role: bluetooth
    - role: rofi
    - role: emacs
    - role: mpv
    - role: qutebrowser
    - role: mimeapps
    - role: gnupg
    - role: ssh
    - role: python
    - role: docker
