---
- hosts: localhost
  connection: local
  become: true
  vars_files: vars.yaml

  roles:
    - role: base
    - role: alacritty
    - role: starship
    - role: git
    - role: i3
    - role: emacs

  tasks:
    - name: Install package
      community.general.pacman:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"

    - name: Clone aur package
      become: false
      ansible.builtin.git:
        repo: "https://aur.archlinux.org/{{ item }}"
        dest: "/tmp/{{ item }}"
      loop: "{{ packages_aur }}"

    - name: Install aur package
      become: false
      ansible.builtin.command:
        cmd: makepkg --install --needed --syncdeps --noconfirm
        chdir: "/tmp/{{ item }}"
      register: result
      changed_when: "'there is nothing to do' not in result.stdout"
      loop: "{{ packages_aur }}"

    - name: Enable and start service
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop: "{{ services }}"

    - name: Use lightdm slick greeter
      ansible.builtin.lineinfile:
        path: /etc/lightdm/lightdm.conf
        regexp: "^[#]?greeter-session="
        line: "greeter-session=lightdm-slick-greeter"
