---
- hosts: localhost
  connection: local
  become: true
  vars_files: vars.yaml

  pre_tasks:
    - name: Sync and refresh
      community.general.pacman:
        update_cache: true

  roles:
    - role: bash
    - role: alacritty
    - role: starship
    - role: git
    - role: i3
    - role: dunst
    - role: volumeicon
    - role: rofi
    - role: emacs
    - role: mpv
    - role: qutebrowser
    - role: mimeapps
    - role: gnupg
    - role: python

  tasks:
    - name: Install package
      community.general.pacman:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"

    - name: Enable and start service
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop: "{{ services }}"

    - name: Use lightdm slick greeter
      ansible.builtin.lineinfile:
        path: /etc/lightdm/lightdm.conf
        regexp: "^[#]?greeter-session="
        line: "greeter-session=lightdm-slick-greeter"
