---
- name: Create directory
  ansible.builtin.file:
    path: "{{ item | ansible.builtin.dirname }}"
    state: directory
    mode: "0755"
  loop: "{{ add_config_files + add_config_templates }}"

- name: Create link
  ansible.builtin.file:
    src: "{{ ansible_parent_role_paths[0] }}/files/{{ item | ansible.builtin.basename | regex_replace('^\\.', '') }}"  # yamllint disable-line rule:line-length
    dest: "{{ item }}"
    state: link
    force: "{{ add_config_file_force }}"
  loop: "{{ add_config_files }}"

- name: Create file
  ansible.builtin.template:
    src: "{{ ansible_parent_role_paths[0] }}/templates/{{ item | ansible.builtin.basename | regex_replace('^\\.', '') }}.j2"  # yamllint disable-line rule:line-length
    dest: "{{ item }}"
    mode: "0644"
  loop: "{{ add_config_templates }}"
