---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ qutebrowser_packages }}"
    state: latest

- name: Link config files
  ansible.builtin.include_role:
    name: link_config
  vars:
    link_config_files: "{{ qutebrowser_config_files }}"
