---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ qutebrowser_packages }}"
    state: latest
  when: can_become

- name: Add config
  ansible.builtin.include_role:
    name: add_config
  vars:
    add_config_files: "{{ qutebrowser_config_files }}"
