[theme]
theme = "semi-native"

[icons]
icons = "awesome4"

[[block]]
block = "cpu"
format = " $icon $utilization "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
format = " $icon $available "

[[block]]
block = "battery"
format = " $icon $percentage "

[[block]]
block = "sound"
driver = "alsa"
show_volume_when_muted = true
format = " $icon $volume "
[[block.click]]
button = "left"
cmd = "alacritty -e alsamixer"

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%Y-%d-%m %R') "
