---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ bluetooth_packages }}"
    state: latest

- name: Enable and start service
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ bluetooth_services }}"
  when: ansible_facts.virtualization_type != "docker"
