---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ bluetooth_packages[ansible_facts.os_family] }}"
    state: latest
  when: can_become

- name: Enable and start service
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ bluetooth_services }}"
  when: ansible_facts.virtualization_type != "docker" and can_become
