---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ python_packages }}"
    state: latest

- name: Install python package
  ansible.builtin.pip:
    name: "{{ python_pip_packages }}"

- name: Install python package (pipx)
  community.general.pipx:
    name: "{{ item }}"
  loop: "{{ python_pipx_packages }}"
