---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ python_packages }}"
    state: latest

- name: Install python package (pipx)
  community.general.pipx:
    name: "{{ item }}"
    executable: /usr/bin/pipx
  loop: "{{ python_pipx_packages }}"
