---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ python_packages[ansible_facts.os_family] }}"
    state: latest
  when: can_become

- name: Install python package (pipx)
  community.general.pipx:
    name: "{{ item }}"
    executable: /usr/bin/pipx
  loop: "{{ python_pipx_packages }}"
