---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ gnupg_packages }}"
    state: latest

- name: Create directory
  ansible.builtin.file:
    path: "{{ gnupg_config_dir }}"
    state: directory
    mode: "0700"

- name: Create link
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ gnupg_config_dir }}/{{ item }}"
    state: link
  loop: "{{ gnupg_config_files }}"
