---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ ssh_packages }}"
    state: latest

- name: Create directory
  ansible.builtin.file:
    path: "{{ ssh_config_dir }}"
    state: directory
    mode: "0700"

- name: Create ssh key
  community.crypto.openssh_keypair:
    backend: "cryptography"
    path: "{{ ssh_config_dir }}/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: false
    regenerate: never
