---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ ssh_packages }}"

- name: Create directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  loop:
    - "{{ ssh_config_dir }}"

- name: Create ssh key
  community.crypto.openssh_keypair:
    backend: "cryptography"
    path: "{{ ssh_config_dir }}/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: false
    regenerate: never
