---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ ssh_packages[ansible_facts.os_family] }}"
    state: latest

- name: Create directory
  ansible.builtin.file:
    path: "{{ ssh_config_dir }}"
    state: directory
    mode: "0700"

- name: Create config file if it does not exists
  ansible.builtin.copy:
    content: ""
    dest: "{{ ssh_config_dir }}/config"
    force: false
    mode: "0600"

- name: Include other config files
  ansible.builtin.lineinfile:
    path: "{{ ssh_config_dir }}/config"
    regexp: "Include ./*.conf"
    line: "Include ./*.conf"

- name: Create ssh key
  community.crypto.openssh_keypair:
    backend: "cryptography"
    path: "{{ ssh_config_dir }}/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: false
    regenerate: never
