import = ["/home/claes/.config/alacritty/local.toml"]
ipc_socket = true
live_config_reload = true

[bell]
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.normal]
family = "TerminessNerdFontMono"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|https:|http:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
action = "Paste"
post_processing = true
regex = '([[:alnum:]]|[[:punct:]])+(\.)[[:alnum:]]+'

[hints.enabled.binding]
key = "P"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
action = "Paste"
post_processing = true
regex = "[0-9a-f]{5,40}"

[hints.enabled.binding]
key = "S"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[window]
opacity = 0.7

[window.padding]
x = 2
y = 2
