---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ i3_packages[ansible_facts.os_family] }}"
    state: latest

- name: Install aur package
  ansible.builtin.include_role:
    name: aur_package
  vars:
    aur_package_names: "{{ i3_packages_aur }}"
  when: ansible_facts.os_family == "Archlinux"

- name: Download i3lock-color
  ansible.builtin.get_url:
    url: https://github.com/Raymo111/i3lock-color/releases/latest/download/i3lock  # yamllint disable-line rule:line-length
    dest: ~/.local/bin/i3lock
    mode: "0775"
  when: ansible_facts.os_family == "Debian"

- name: Link config files
  ansible.builtin.include_role:
    name: link_config
  vars:
    link_config_files: "{{ i3_config_files }}"
