---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ i3_packages[ansible_facts.os_family] }}"
    state: latest
  when: can_become

- name: Install aur package
  ansible.builtin.include_role:
    name: aur_package
  vars:
    aur_package_names: "{{ i3_packages_aur }}"
  when: ansible_facts.os_family == "Archlinux"

- name: Download i3lock-color
  ansible.builtin.get_url:
    url: https://github.com/Raymo111/i3lock-color/releases/latest/download/i3lock  # yamllint disable-line rule:line-length
    dest: ~/.local/bin/i3lock
    mode: "0775"
  when: ansible_facts.os_family == "Debian"

- name: Build i3status-rs
  when: ansible_facts.os_family == "Debian" and ansible_facts.virtualization_type != "docker"  # yamllint disable-line rule:line-length
  block:
    - name: Create temporary directory
      ansible.builtin.file:
        path: /tmp/docker-rust
        state: directory
        mode: "0755"

    - name: Build i3status-rs inside docker container
      community.general.docker_container:
        name: i3status-rs_installer
        image: rust
        command: bash -c "apt update && apt install --yes libpulse-dev libsensors-dev && cargo install i3status-rs --target-dir /tmp"  # yamllint disable-line rule:line-length
        cleanup: true
        detach: false
        volumes:
          - /tmp/docker-rust/:/tmp/release

    - name: Copy i3status-rs binary to ~/.local/bin
      ansible.builtin.copy:
        src: /tmp/docker-rust/i3status-rs
        dest: ~/.local/bin/
        remote_src: true
        mode: "0755"

- name: Add config
  ansible.builtin.include_role:
    name: add_config
  vars:
    add_config_files: "{{ i3_config_files }}"
