---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ git_packages }}"

- name: Install aur package
  ansible.builtin.include_role:
    name: aur_package
  vars:
    aur_packages: "{{ git_packages_aur }}"

- name: Link config files
  ansible.builtin.include_role:
    name: link_config
  vars:
    config_files: "{{ git_config_files}}"
