---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ git_packages[ansible_facts.os_family] }}"
    state: latest
  when: can_become

- name: Install aur package
  ansible.builtin.include_role:
    name: aur_package
  vars:
    aur_package_names: "{{ git_packages_aur }}"
  when: ansible_facts.os_family == "Archlinux"

- name: Build delta
  when: ansible_facts.os_family == "Debian" and ansible_facts.virtualization_type != "docker"  # yamllint disable-line rule:line-length
  block:
    - name: Create temporary directory
      ansible.builtin.file:
        path: /tmp/docker-rust
        state: directory
        mode: "0755"

    - name: Build inside docker container
      community.general.docker_container:
        name: delta_installer
        image: rust
        command: cargo install git-delta --target-dir /tmp
        cleanup: true
        detach: false
        volumes:
          - /tmp/docker-rust/:/tmp/release

    - name: Copy binary to ~/.local/bin
      ansible.builtin.copy:
        src: /tmp/docker-rust/delta
        dest: ~/.local/bin/
        remote_src: true
        mode: "0755"

- name: Build diffr
  when: ansible_facts.os_family == "Debian" and ansible_facts.virtualization_type != "docker"  # yamllint disable-line rule:line-length
  block:
    - name: Create temporary directory
      ansible.builtin.file:
        path: /tmp/docker-rust
        state: directory
        mode: "0755"

    - name: Build inside docker container
      community.general.docker_container:
        name: diffr_installer
        image: rust
        command: cargo install diffr --target-dir /tmp
        cleanup: true
        detach: false
        volumes:
          - /tmp/docker-rust/:/tmp/release

    - name: Copy binary to ~/.local/bin
      ansible.builtin.copy:
        src: /tmp/docker-rust/diffr
        dest: ~/.local/bin/
        remote_src: true
        mode: "0755"

- name: Add config
  ansible.builtin.include_role:
    name: add_config
  vars:
    add_config_templates: "{{ git_config_templates }}"
