---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ git_packages }}"

- name: Clone aur package
  become: false
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/{{ item }}"
    dest: "/tmp/{{ item }}"
  loop: "{{ git_packages_aur }}"

- name: Install aur package
  become: false
  ansible.builtin.command:
    cmd: makepkg --install --needed --syncdeps --noconfirm
    chdir: "/tmp/{{ item }}"
  register: result
  changed_when: "'there is nothing to do' not in result.stdout"
  loop: "{{ git_packages_aur }}"

- name: Create directory
  become: false
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ git_config_dir }}"

- name: Create link
  become: false
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ git_config_dir }}/{{ item }}"
    state: link
  loop: "{{ git_config_files }}"
