---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ git_packages[ansible_facts.os_family] }}"
    state: latest
  when: can_become

- name: Install aur package
  ansible.builtin.include_role:
    name: aur_package
  vars:
    aur_package_names: "{{ git_packages_aur }}"
  when: ansible_facts.os_family == "Archlinux"

- name: Add config
  ansible.builtin.include_role:
    name: add_config
  vars:
    add_config_templates: "{{ git_config_templates }}"
