---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ emacs_packages }}"
    state: latest

- name: Link config files
  ansible.builtin.include_role:
    name: link_config
  vars:
    link_config_files: "{{ emacs_config_files }}"
