---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ rofi_packages[ansible_facts.os_family] }}"
    state: latest

- name: Install aur package
  ansible.builtin.include_role:
    name: aur_package
  vars:
    aur_package_names: "{{ rofi_packages_aur }}"
  when: ansible_facts.os_family == "Archlinux"

- name: Download rofi-pass
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/carnager/rofi-pass/master/rofi-pass
    dest: ~/.local/bin
    mode: "0775"
  when: ansible_facts.os_family == "Debian"

- name: Download rofi-bluetooth
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nickclyde/rofi-bluetooth/master/rofi-bluetooth  # yamllint disable-line rule:line-length
    dest: ~/.local/bin
    mode: "0775"
  when: ansible_facts.os_family == "Debian"

- name: Download rofi-power-menu
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jluttine/rofi-power-menu/master/rofi-power-menu  # yamllint disable-line rule:line-length
    dest: ~/.local/bin
    mode: "0775"
  when: ansible_facts.os_family == "Debian"

- name: Add config
  ansible.builtin.include_role:
    name: add_config
  vars:
    add_config_files: "{{ rofi_config_files }}"
