---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ rofi_packages }}"

- name: Install aur package
  ansible.builtin.include_role:
    name: aur_package
  vars:
    aur_package_names: "{{ rofi_packages_aur }}"

- name: Link config files
  ansible.builtin.include_role:
    name: link_config
  vars:
    link_config_files: "{{ rofi_config_files }}"
