---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ rofi_packages[ansible_facts.os_family] }}"
    state: latest

- name: Install aur package
  ansible.builtin.include_role:
    name: aur_package
  vars:
    aur_package_names: "{{ rofi_packages_aur }}"
  when: ansible_facts.os_family == "Archlinux"

- name: Download rofi-pass
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/carnager/rofi-pass/master/rofi-pass
    dest: ~/.local/bin
    mode: "0775"
  when: ansible_facts.os_family == "Debian"

- name: Link config files
  ansible.builtin.include_role:
    name: link_config
  vars:
    link_config_files: "{{ rofi_config_files }}"
