#+TITLE: Emacs Configuration
#+AUTHOR: Claes Hallstrom
#+OPTIONS: toc:nil num:nil
#+STARTUP: overview

* Package Management

Next-generation, purely functional package manager for the Emacs hacker.

#+begin_src emacs-lisp
(setq straight-check-for-modifications '(check-on-save find-when-checking))
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
#+end_src

A use-package declaration for simplifying your .emacs.

#+begin_src emacs-lisp
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)
#+end_src

* Cleaning

Help keeping emacs-user-directory clean.

#+begin_src emacs-lisp
(use-package no-littering
  :config
  (setq auto-save-file-name-transforms
        `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))
  (setq custom-file (no-littering-expand-etc-file-name "custom.el"))
  (when (file-exists-p custom-file)
    (load-file custom-file)))
#+end_src

* Appearance

Configure the appearance of Emacs.

#+begin_src emacs-lisp
(use-package emacs
  :init
  (global-hl-line-mode 1)
  (global-display-line-numbers-mode t)
  :custom
  (initial-scratch-message nil)
  (column-number-mode t)
  (visible-bell t)
  :config
  (set-window-scroll-bars (minibuffer-window) nil nil)
  (set-frame-parameter (selected-frame) 'alpha '(95 . 95))
  (add-to-list 'default-frame-alist `(alpha . ,'(95 . 95))))
#+end_src

Emacs mode for wrapping visual-line-mode buffers at fill-column.

#+begin_src emacs-lisp
(use-package visual-fill-column
  :custom
  (visual-fill-column-width 50)
  (visual-fill-column-center-text t))
#+end_src

An opinionated pack of modern color-themes.

#+begin_src emacs-lisp
(use-package doom-themes
  :init (load-theme 'doom-material t))
#+end_src

A fancy and fast mode-line inspired by minimalism design.

#+begin_src emacs-lisp
(use-package doom-modeline
  :hook (after-init . doom-modeline-mode)
  :custom
  (doom-modeline-buffer-encoding nil)
  (doom-modeline-minor-modes t)
  (doom-modeline-buffer-file-name-style 'truncate-except-project)
  :config
  (setq doom-modeline-icon t))
#+end_src

A minor-mode menu for the mode line.

#+begin_src emacs-lisp
(use-package minions
  :hook (doom-modeline-mode . minions-mode))
#+end_src

A utility package to collect various Icon Fonts and propertize them within Emacs.

#+begin_src emacs-lisp
(use-package all-the-icons)
#+end_src

* Completion

VERTical Interactive COmpletion.

#+begin_src emacs-lisp
(use-package vertico
  :hook
  (after-init . vertico-mode))
#+end_src

Simple but effective sorting and filtering for Emacs.

#+begin_src emacs-lisp
(use-package prescient
  :after vertico
  :config
  (prescient-persist-mode 1))
#+end_src

Emacs completion style that matches multiple regexps in any order.

#+begin_src emacs-lisp
(use-package orderless
  :init
  (setq completion-category-defaults nil)
  :custom
  (completion-styles '(orderless))
  (completion-category-overrides '((file (styles . (basic partial-completion))))))
#+end_src

Marginalia in the minibuffer.

#+begin_src emacs-lisp
(use-package marginalia
  :custom
  (marginalia-annotators '(marginalia-annotators-heavy marginalia-annotators-light nil))
  :hook
  (vertico-mode . marginalia-mode))
#+end_src

Consulting completing-read.

#+begin_src emacs-lisp
(use-package consult
  :bind (("C-x b" . consult-buffer)
         ("C-x 4 b" . consult-buffer-other-window)
         ("C-x 5 b" . consult-buffer-other-frame)
         ("M-y" . consult-yank-pop)
         ("M-g g" . consult-goto-line)
         ("M-g M-g" . consult-goto-line)
         ("M-g o" . consult-outline)
         ("M-g m" . consult-mark)
         ("M-g k" . consult-global-mark)
         ("M-g i" . consult-imenu)
         ("M-g I" . consult-imenu-multi)
         ("M-s f" . consult-find)
         ("M-s F" . consult-locate)
         ("M-s g" . consult-grep)
         ("M-s G" . consult-git-grep)
         ("M-s r" . consult-ripgrep)
         ("M-s l" . consult-line)
         ("M-s L" . consult-line-multi)
         ("M-s m" . consult-multi-occur)
         ("M-s k" . consult-keep-lines)
         ("M-s u" . consult-focus-lines)
         ("M-s e" . consult-isearch-history))
  :init
  (setq register-preview-delay 0)
  (setq register-preview-function #'consult-register-format)
  (advice-add #'completing-read-multiple
              :override #'consult-completing-read-multiple)
  (setq xref-show-xrefs-function #'consult-xref)
  (setq xref-show-definitions-function #'consult-xref)
  (setq completion-in-region-function #'consult-completion-in-region)
  :config
  (recentf-mode 1)
  (setq consult-narrow-key "<")
  (setq consult-project-root-function
        (lambda ()
          (when-let (project (project-current))
            (car (project-roots project))))))
#+end_src

Emacs Mini-Buffer Actions Rooted in Keymaps.

#+begin_src emacs-lisp
(use-package embark
  :bind ("C-," . embark-act)
  :init
  (setq prefix-help-command #'embark-prefix-help-command))

(use-package embark-consult
  :after (embark consult))
#+end_src

Dynamic abbreviation package.

#+begin_src emacs-lisp
(use-package dabbrev
  :straight (:type built-in)
  :custom
  (dabbrev-case-replace nil)
  (dabbrev-backward-only nil)
  (dabbrev-case-distinction nil)
  (dabbrev-case-fold-search t)
  (dabbrev-check-all-buffers t)
  (dabbrev-abbrev-char-regexp nil)
  (dabbrev-eliminate-newlines nil)
  (dabbrev-check-other-buffers t)
  (dabbrev-upcase-means-case-search t)
  :config
  (defun dabbrev-expand-or-completion ()
    (interactive)
    (if (not (eq 'dabbrev-expand-or-completion last-command))
        (dabbrev-expand nil)
      (undo)  ;; Undo dabbrev-expand from last time
      (dabbrev-completion 16)))
  :bind
  ("C-." . dabbrev-expand-or-completion))
#+end_src

Save minibuffer history.

#+begin_src emacs-lisp
(use-package savehist
  :straight (:type built-in)
  :init (savehist-mode))
#+end_src

* Project

Operations on the current project.

#+begin_src emacs-lisp
(use-package project)
#+end_src

* Files

Dired, the Directory Editor.

#+begin_src emacs-lisp
(use-package dired
  :straight (:type built-in)
  :commands (dired dired-jump)
  :bind (("C-x C-j" . dired-jump))
  :custom ((dired-listing-switches "-aghov --group-directories-first")))
#+end_src

Reuse the current dired buffer to visit a directory.

#+begin_src emacs-lisp
(use-package dired-single
  :after dired
  :bind
  (:map dired-mode-map
        ([remap dired-find-file] . dired-single-buffer)
        ([remap dired-up-directory] . dired-single-up-directory)))
#+end_src

* Buffers

Operate on buffers like dired.

#+begin_src emacs-lisp
(use-package ibuffer
  :straight (:type built-in)
  :bind
  (("C-x C-b" . ibuffer)
   ("C-x k" . kill-this-buffer)))
#+end_src

* Windows

Quickly switch windows in Emacs.

#+begin_src emacs-lisp
(use-package ace-window
  :bind ("C-x o" . ace-window)
  :custom
  (aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l)))
#+end_src

* Searching/Jumping

An Emacs frontend to The Silver Searcher.

#+begin_src emacs-lisp
(use-package ag
  :commands ag)
#+end_src

Emacs search tool based on ripgrep.

#+begin_src emacs-lisp
(use-package rg
  :commands rg)
#+end_src

An Emacs "jump to definition" package for 40+ languages.

#+begin_src emacs-lisp
(use-package dumb-jump
  :config
  (setq dumb-jump-force-searcher 'ag)
  (add-hook 'xref-backend-functions #'dumb-jump-xref-activate))
#+end_src

* Version Control

It's Magit! A Git porcelain inside Emacs.

#+begin_src emacs-lisp
(use-package magit
  :commands (magit-status magit-get-current-branch)
  :custom
  (magit-display-buffer-function
   #'magit-display-buffer-fullframe-status-v1))

(use-package git-commit
  :after magit
  :config
  (setq git-commit-summary-max-length 50)
  (add-hook 'git-commit-mode-hook
            '(lambda ()
               (setq fill-column 72)
               (setq-local comment-auto-fill-only-comments nil))))
#+end_src

Work with Git forges from the comfort of Magit.

#+begin_src emacs-lisp
(use-package forge
  :after magit)
#+end_src

Example of ~/.authinfo for github.

#+begin_example conf
machine api.github.com login claha^forge password TOKEN
#+end_example

GnuPG Pinentry server implementation.

#+begin_src emacs-lisp
(unless (eq system-type 'windows-nt)
  (use-package pinentry
    :custom
    (epg-pinentry-mode 'loopback)
    :init
    (setenv "INSIDE_EMACS" (format "%s,comint" emacs-version))
    (pinentry-start)))
#+end_src

Emacs package for highlighting uncommitted changes.

#+begin_src emacs-lisp
(use-package diff-hl
  :hook ((prog-mode . diff-hl-mode)
         (org-mode . diff-hl-mode)
         (text-mode . diff-hl-mode)
         (dired-mode . diff-hl-dired-mode))
  :custom
  (diff-hl-side 'right))
#+end_src

* Editing

Convert the region to lower or upper case.

#+begin_src emacs-lisp
(use-package emacs
  :config
  (put 'downcase-region 'disabled nil)
  (put 'upcase-region 'disabled nil))
#+end_src

Restrict editing in this buffer to the current region.

#+begin_src emacs-lisp
(use-package emacs
  :config
  (put 'narrow-to-region 'disabled nil))
#+end_src

Enables hungry deletion in all modes.

#+begin_src emacs-lisp
(use-package hungry-delete
  :custom
  (hungry-delete-join-reluctantly t)
  :hook
  (after-init . global-hungry-delete-mode))
#+end_src

Writable grep buffer and apply the changes to files.

#+begin_src emacs-lisp
(use-package wgrep)
#+end_src

* Programming

#+begin_src emacs-lisp
(use-package yaml-mode
  :defer t)

(use-package cmake-mode
  :defer t)

(use-package flycheck
  :hook (prog-mode . flycheck-mode))
#+end_src

** General

Tabs are evil, use 4 spaces as default.

#+begin_src emacs-lisp
(use-package emacs
  :config
  (setq-default indent-tabs-mode nil)
  (setq-default tab-width 4))
#+end_src

Run compiler as inferior of Emacs, parse error messages.

#+begin_src emacs-lisp
(use-package compile
  :straight (:type built-in)
  :custom
  (compilation-ask-about-save nil)
  (compilation-always-kill t)
  (compilation-scroll-output 'first-error))
#+end_src

Translate ANSI escape sequences into faces.

#+begin_src emacs-lisp
(use-package ansi-color
  :straight (:type built-in)
  :hook (compilation-filter . colorize-compilation-buffer)
  :config
  (defun colorize-compilation-buffer ()
    (ansi-color-apply-on-region compilation-filter-start (point))))
#+end_src

Highlight matching paren.

#+begin_src emacs-lisp
(use-package paren
  :straight (:type built-in)
  :init
  (show-paren-mode 1)
  :custom
  (show-paren-delay 0.0))
#+end_src

Toggle automatic parens pairing.

#+begin_src emacs-lisp
(use-package electric-pair
  :straight (:type built-in)
  :hook (prog-mode . electric-pair-mode))
#+end_src

** Docker

Manage docker from Emacs.

#+begin_src emacs-lisp
(use-package docker
  :commands docker)
#+end_src

An emacs mode for handling Dockerfiles.

#+begin_src emacs-lisp
(use-package dockerfile-mode)
#+end_src

TRAMP integration for docker containers.

#+begin_src emacs-lisp
(use-package docker-tramp
  :custom
  (docker-tramp-use-names t))
#+end_src

** Python

Python virtual environment interface for Emacs.

#+begin_src emacs-lisp
(use-package pyvenv
  :hook (python-mode . pyvenv-mode)
  :bind
  (:map python-mode-map
        ("C-c C-a" . pyvenv-activate)))
#+end_src

Python Black for Emacs.

#+begin_src emacs-lisp
(use-package blacken
  :after python
  :bind
  (:map python-mode-map
        ("C-c C-b" . blacken-buffer)))
#+end_src

** C/C++

Major mode for editing C and similar languages.

#+begin_src emacs-lisp
(use-package cc-mode
  :straight (:type built-in)
  :defer t
  :custom
  (c-default-style "linux")
  (c-basic-offset 2)
  :config
  (c-set-offset 'case-label '+))
#+end_src

* Shell/Terminal

Hide line numbers in terminals and shells.

#+begin_src emacs-lisp
(use-package shell
  :straight (:type built-in)
  :commands shell
  :config
  (add-hook 'shell-mode-hook (lambda () (display-line-numbers-mode 0))))

(use-package eshell
  :straight (:type built-in)
  :commands eshell
  :custom
  (eshell-banner-message "")
  (eshell-highlight-prompt t)
  (eshell-prompt-function 'eshell-prompt)
  (eshell-prompt-regexp "^$ ")
  :config
  (add-hook 'eshell-mode-hook (lambda () (display-line-numbers-mode 0)))
  (defun get-prompt-path ()
    (let* ((current-path (eshell/pwd))
           (git-output (shell-command-to-string "git rev-parse --show-toplevel"))
           (has-path (not (string-match "^fatal" git-output))))
      (if (not has-path)
          (abbreviate-file-name current-path)
        (string-remove-prefix (file-name-directory git-output) current-path))))
  (defun eshell-prompt ()
    (let ((current-branch (magit-get-current-branch)))
      (concat
       (propertize (get-prompt-path) 'face `(:foreground "cyan"))
       (when current-branch
         (concat
          (propertize " • " 'face `(:foreground "white"))
          (propertize (concat " " current-branch) 'face `(:foreground "violet"))))
       (propertize " • " 'face `(:foreground "white"))
       (propertize (format-time-string "%I:%M:%S %p") 'face `(:foreground "teal"))
       (if (= (user-uid) 0)
           (propertize "\n#" 'face `(:foreground "red"))
         (propertize "\n$" 'face `(:foreground "green")))
       (propertize " " 'face `(:foreground "white"))))))

(use-package term
  :straight (:type built-in)
  :commands term
  :config
  (add-hook 'term-mode-hook (lambda () (display-line-numbers-mode 0))))
#+end_src

* Org mode

Org mode is for keeping notes, maintaining TODO lists, planning projects, and authoring documents with a fast and effective plain-text system.

#+begin_src emacs-lisp
(use-package org
  :straight (:type built-in)
  :config
  (defun org-mode-setup ()
    (display-line-numbers-mode 0)
    (visual-line-mode 1)
    (org-indent-mode))
  (setq org-ellipsis " ▾")
  (setq org-hide-emphasis-markers t)
  :hook (org-mode . org-mode-setup))
#+end_src

UTF-8 bullets for org-mode.

#+begin_src emacs-lisp
(use-package org-bullets
  :after org
  :hook (org-mode . org-bullets-mode)
  :custom
  (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))
#+end_src

Configure org source code blocks.

#+begin_src emacs-lisp
(use-package org-src
  :straight (:type built-in)
  :after org
  :config
  (setq org-src-window-setup 'current-window)
  (setq org-src-fontify-natively t)
  (setq org-src-preserve-indentation t)
  (setq org-src-tab-acts-natively t))
#+end_src

Ultra-minimalist presentation minor-mode for Emacs org-mode.

#+begin_src emacs-lisp
(use-package org-present
  :after org
  :config
  (defun org-present-hook ()
    (setq-local face-remapping-alist '((default (:height 1.5) variable-pitch)
                                       (header-line (:height 4.5) variable-pitch)
                                       (org-document-title (:height 1.75) org-document-title)
                                       (org-code (:height 1.55) org-code)
                                       (org-verbatim (:height 1.55) org-verbatim)
                                       (org-block (:height 1.25) org-block)
                                       (org-block-begin-line (:height 0.7) org-block)))
    (setq header-line-format " ")
    (org-present-big)
    (org-present-read-only)
    (org-present-beginning)
    (visual-fill-column-mode +1)
    (global-hl-line-mode -1))
  (defun org-present-quit-hook ()
    (setq-local face-remapping-alist nil)
    (setq header-line-format nil)
    (org-present-small)
    (org-present-read-write)
    (org-present-show-cursor)
    (visual-fill-column-mode -1)
    (global-hl-line-mode +1))
  (defun org-present-prepare (buffer-name heading)
    (org-overview)
    (org-show-entry)
    (org-show-children))
  (setq org-present-after-navigate-functions 'org-present-prepare)
  :hook ((org-present-mode . org-present-hook)
         (org-present-mode-quit . org-present-quit-hook))
#+end_src

* Help

A better Emacs *help* buffer.

#+begin_src emacs-lisp
(use-package helpful
  :bind
  ([remap describe-command] . helpful-command)
  ([remap describe-function] . helpful-callable)
  ([remap describe-key] . helpful-key)
  ([remap describe-symbol] . helpful-symbol)
  ([remap describe-variable] . helpful-variable))
#+end_src

tldr client for Emacs.

#+begin_src emacs-lisp
(use-package tldr
  :commands tldr)
#+end_src

* Miscellaneous

Miscellaneous packages.

#+begin_src emacs-lisp
(use-package hydra
  :defer t)
#+end_src

Use qutebrowser to browse.

#+begin_src emacs-lisp
(use-package emacs
  :config
  (setq browse-url-browser-function
        '(("." . browse-url-generic)))
  (setq browse-url-generic-program "qutebrowser"))
#+end_src

Random stuff...

#+begin_src emacs-lisp
(use-package emacs
  :config
  (setq use-short-answers t)
  (setq large-file-warning-threshold nil)
  (setq vc-follow-symlinks t)
  (global-unset-key (kbd "<C-down-mouse-1>"))
  (global-unset-key (kbd "<C-down-mouse-2>"))
  (global-unset-key (kbd "<C-down-mouse-3>"))
  (global-unset-key (kbd "<S-down-mouse-1>"))
  (global-unset-key (kbd "<S-down-mouse-2>"))
  (global-unset-key (kbd "<S-down-mouse-3>"))
  :custom
  (minibuffer-prompt-properties
   '(read-only t cursor-intangible t face minibuffer-prompt)))
#+end_src

* Local

Load local file if it exists and is readable.

#+begin_src emacs-lisp
(use-package emacs
  :config
  (let ((local-file (expand-file-name "local.el" user-emacs-directory)))
    (if (file-readable-p local-file)
        (load-file local-file))))
#+end_src
