---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ volumeicon_packages }}"

- name: Link config files
  ansible.builtin.include_role:
    name: link_config
  vars:
    config_files: "{{ volumeicon_config_files }}"
