---
python_packages:
  Archlinux:
    - python
    - python-pip
    - python-pipx
  Debian:
    - python3
    - python3-pip
    - python-is-python3
    - pipx
python_pipx_packages:
  - ansible
  - black
  - flake8
  - isort
  - pre-commit
  - pylint
  - pytest
