---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ aur_package_packages }}"

- name: Clone aur package
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/{{ item }}"
    dest: "/tmp/{{ item }}"
  changed_when: false
  loop: "{{ aur_package_names }}"

- name: Install aur package
  ansible.builtin.command:
    cmd: makepkg --install --needed --syncdeps --noconfirm
    chdir: "/tmp/{{ item }}"
  register: aur_package_install
  changed_when: "'there is nothing to do' not in aur_package_install.stdout"
  loop: "{{ aur_package_names }}"
