---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ lightdm_packages }}"

- name: Use lightdm slick greeter
  become: true
  ansible.builtin.lineinfile:
    path: "{{ lightdm_config_dir }}/lightdm.conf"
    regexp: "^[#]?greeter-session="
    line: "greeter-session=lightdm-slick-greeter"

- name: Create link
  become: true
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ lightdm_config_dir }}/{{ item }}"
    state: link
  loop: "{{ lightdm_config_files }}"

- name: Create backgrounds dir
  become: true
  ansible.builtin.file:
    path: "/usr/share/backgrounds"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Add backgrounds
  become: true
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/usr/share/backgrounds/{{ item }}"
    state: link
  loop: "{{ lightdm_backgrounds }}"

- name: Enable and start service
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ lightdm_services }}"
  when: ansible_facts.virtualization_type != "docker"
