---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ lightdm_packages }}"

- name: Enable and start service
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ lightdm_services }}"

- name: Use lightdm slick greeter
  ansible.builtin.lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: "^[#]?greeter-session="
    line: "greeter-session=lightdm-slick-greeter"
