---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ lightdm_packages }}"

- name: Enable and start service
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ lightdm_services }}"

- name: Use lightdm slick greeter
  ansible.builtin.lineinfile:
    path: "{{ lightdm_config_dir }}/lightdm.conf"
    regexp: "^[#]?greeter-session="
    line: "greeter-session=lightdm-slick-greeter"

- name: Create link
  become: true
  ansible.builtin.file:
    src: "{{ role_path}}/files/{{ item }}"
    dest: "{{ lightdm_config_dir }}/{{ item }}"
    state: link
  loop: "{{ lightdm_config_files }}"

- name: Create link
  become: true
  ansible.builtin.file:
    src: "{{ role_path}}/files/{{ item }}"
    dest: "/usr/share/backgrounds/{{ item }}"
    state: link
  loop: "{{ lightdm_backgrounds }}"
