---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ lightdm_packages }}"
    state: latest

- name: Use lightdm slick greeter
  become: true
  ansible.builtin.lineinfile:
    path: "{{ lightdm_config_dir }}/lightdm.conf"
    regexp: "^[#]?greeter-session="
    line: "greeter-session=lightdm-slick-greeter"

- name: Create slick greeter config
  become: true
  ansible.builtin.template:
    src: "{{ role_path }}/templates/slick-greeter.conf.j2"
    dest: "{{ lightdm_config_dir }}/slick-greeter.conf"
    mode: "0644"

- name: Enable and start service
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ lightdm_services }}"
  when: ansible_facts.virtualization_type != "docker"
