#+TITLE: Emacs Configuration
#+AUTHOR: Claes Hallstrom
#+OPTIONS: toc:nil num:nil
#+STARTUP: overview

* Package Management

Package system for Emacs.

#+begin_src emacs-lisp
(require 'package)
(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))
#+end_src

A use-package declaration for simplifying your .emacs.

#+begin_src emacs-lisp
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(require 'use-package)
#+end_src

* Cleaning

Help keeping emacs-user-directory clean.

#+begin_src emacs-lisp
(use-package no-littering
  :ensure t
  :config
  (setq auto-save-file-name-transforms
        `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))
  (setq custom-file (no-littering-expand-etc-file-name "custom.el")))
#+end_src

* Appearance

Configure the appearance of Emacs.

#+begin_src emacs-lisp
(use-package emacs
  :init
  (global-hl-line-mode 1)
  (show-paren-mode 1)
  (global-display-line-numbers-mode t)
  :custom
  (initial-scratch-message nil)
  (show-paren-delay 0.0)
  (column-number-mode t)
  (visible-bell t)
  :config
  (set-window-scroll-bars (minibuffer-window) nil nil)
  (set-frame-parameter (selected-frame) 'alpha '(90 . 90))
  (add-to-list 'default-frame-alist `(alpha . ,'(90 . 90))))
#+end_src

An opinionated pack of modern color-themes.

#+begin_src emacs-lisp
(use-package doom-themes
  :ensure t
  :init (load-theme 'doom-material t))
#+end_src

Configure mode line without icon and showing minor modes and buffer name.

#+begin_src emacs-lisp
(use-package diminish
  :ensure t
  :after use-package)

(use-package all-the-icons
  :ensure t)

(use-package doom-modeline
  :ensure t
  :hook (after-init . doom-modeline-mode)
  :custom
  (doom-modeline-buffer-encoding nil)
  (doom-modeline-minor-modes t)
  (doom-modeline-buffer-file-name-style 'buffer-name)
  :config
  (setq doom-modeline-icon t))
#+end_src

* Completion

Better solution for incremental narrowing in Emacs.

#+begin_src emacs-lisp
(use-package selectrum
  :ensure t
  :custom
  (selectrum-fix-vertical-window-height t)
  (selectrum-max-window-height 9)
  (selectrum-show-indices t)
  (selectrum-extend-current-candidate-highlight t)
  (selectrum-highlight-candidates-function #'orderless-highlight-matches)
  :hook
  (after-init . selectrum-mode))
#+end_src

Simple but effective sorting and filtering for Emacs.

#+begin_src emacs-lisp
(use-package prescient
  :ensure t
  :after selectrum
  :config
  (prescient-persist-mode 1))

(use-package selectrum-prescient
  :ensure t
  :after (selectrum prescient)
  :custom
  (selectrum-prescient-enable-filtering nil)
  :config
  (selectrum-prescient-mode 1))
#+end_src

Emacs completion style that matches multiple regexps in any order.

#+begin_src emacs-lisp
(use-package orderless
  :ensure t
  :custom
  (completion-styles '(orderless))
  (orderless-skip-highlighting (lambda () selectrum-is-active)))
#+end_src

Marginalia in the minibuffer.

#+begin_src emacs-lisp
(use-package marginalia
  :ensure t
  :custom
  (marginalia-annotators '(marginalia-annotators-heavy marginalia-annotators-light nil))
  :hook
  (selectrum-mode . marginalia-mode))
#+end_src

Consulting completing-read.

#+begin_src emacs-lisp
(use-package consult
  :ensure t
  :bind (("C-x b" . consult-buffer)
         ("C-x 4 b" . consult-buffer-other-window)
         ("C-x 5 b" . consult-buffer-other-frame)
         ("M-g M-g" . consult-goto-line)
         ("M-g o" . consult-outline)
         ("M-g i" . consult-imenu)
         ("M-g I" . consult-project-imenu)
         ("M-s f" . consult-find)
         ("M-s L" . consult-locate)
         ("M-s g" . consult-grep)
         ("M-s G" . consult-git-grep)
         ("M-s r" . consult-ripgrep)
         ("M-s l" . consult-line)
         ("M-s m" . consult-multi-occur)
         ("M-s k" . consult-keep-lines)
         ("M-s u" . consult-focus-lines))
  :init
  (setq register-preview-delay 0)
  (setq register-preview-function #'consult-register-format)
  (setq xref-show-xrefs-function #'consult-xref)
  (setq xref-show-definitions-function #'consult-xref)
  :config
  (recentf-mode 1)
  (setq consult-narrow-key "<")
  (autoload 'projectile-project-root "projectile")
  (setq consult-project-root-function #'projectile-project-root))
#+end_src

Emacs Mini-Buffer Actions Rooted in Keymaps.

#+begin_src emacs-lisp
(use-package embark
  :ensure t
  :bind ("C-," . embark-act)
  :custom
  (embark-action-indicator
   (lambda (map _target)
     (which-key--show-keymap "Embark" map nil nil 'no-paging)
     #'which-key--hide-popup-ignore-command)
   embark-become-indicator embark-action-indicator))

(use-package embark-consult
  :ensure t
  :after (embark consult))
#+end_src

Modular in-buffer completion framework for Emacs.

#+begin_src emacs-lisp
(use-package company
  :ensure t
  :defer t)
#+end_src

Configure dabbrev.

#+begin_src emacs-lisp
(use-package dabbrev
  :custom
  (dabbrev-abbrev-char-regexp nil)
  (dabbrev-backward-only nil)
  (dabbrev-case-distinction nil)
  (dabbrev-case-fold-search t)
  (dabbrev-case-replace nil)
  (dabbrev-eliminate-newlines nil)
  (dabbrev-upcase-means-case-search t)
  :config
  (global-set-key (kbd "C-.") 'dabbrev-expand)
  (global-set-key (kbd "C-:")
                  '(lambda()
                     (interactive)
                     (let ((current-prefix-arg '(16)))  ;; C-u C-u
                       (call-interactively 'dabbrev-completion)))))
#+end_src

* Project

Project Interaction Library for Emacs.

#+begin_src emacs-lisp
(use-package projectile
  :ensure t
  :diminish projectile-mode
  :bind-keymap
  ("C-c p" . projectile-command-map)
  :config
  (projectile-mode)
  (setq frame-title-format '((:eval (projectile-project-name)))))
#+end_src

* Files

Dired, the Directory Editor.

#+begin_src emacs-lisp
(use-package dired
  :commands (dired dired-jump)
  :bind (("C-x C-j" . dired-jump))
  :custom ((dired-listing-switches "-aghov --group-directories-first")))
#+end_src

* Buffers

Operate on buffers like dired.

#+begin_src emacs-lisp
(use-package ibuffer
  :bind
  (("C-x C-b" . ibuffer)
   ("C-x k" . kill-this-buffer)))
#+end_src

* Windows

Quickly switch windows in Emacs.

#+begin_src emacs-lisp
(use-package ace-window
  :ensure t
  :bind ("C-x o" . ace-window)
  :custom
  (aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l)))
#+end_src

* Searching/Jumping

Jump to things in Emacs tree-style.

#+begin_src emacs-lisp
(use-package avy
  :ensure t
  :defer
  :init
  (avy-setup-default))
#+end_src

An Emacs frontend to The Silver Searcher.

#+begin_src emacs-lisp
(use-package ag
  :ensure t
  :commands ag)
#+end_src

Emacs search tool based on ripgrep.

#+begin_src emacs-lisp
(use-package rg
  :ensure t
  :commands rg)
#+end_src

An Emacs "jump to definition" package for 40+ languages.

#+begin_src emacs-lisp
(use-package dumb-jump
  :ensure t
  :config
  (setq dumb-jump-force-searcher 'ag)
  (add-hook 'xref-backend-functions #'dumb-jump-xref-activate))
#+end_src

* Version Control

It's Magit! A Git porcelain inside Emacs.

#+begin_src emacs-lisp
(use-package magit
  :ensure t
  :custom
  (magit-display-buffer-function
   #'magit-display-buffer-fullframe-status-v1)
  :bind (("C-c g" . magit-status)))

(use-package git-commit
  :ensure t
  :after magit
  :config
  (setq git-commit-summary-max-length 50)
  (add-hook 'git-commit-mode-hook
            '(lambda ()
               (setq fill-column 72)
               (setq-local comment-auto-fill-only-comments nil))))
#+end_src

Work with Git forges from the comfort of Magit.

#+begin_src emacs-lisp
(use-package forge
  :after magit
  :ensure t)
#+end_src

Example of ~/.authinfo for github.

#+begin_example conf
machine api.github.com login claha^forge password TOKEN
#+end_example

GnuPG Pinentry server implementation.

#+begin_src emacs-lisp
(use-package pinentry
  :ensure t
  :hook
  (after-init . pinentry-start)
  :custom
  (epg-pinentry-mode 'loopback))
#+end_src

Example of ~/.gnupg/gpg-agent.conf.

#+begin_example conf
allow-emacs-pinentry
allow-loopback-pinentry
#+end_example

Emacs package for highlighting uncommitted changes

#+begin_src emacs-lisp
(use-package diff-hl
  :ensure t
  :hook ((prog-mode . diff-hl-mode)
         (org-mode . diff-hl-mode)
         (dired-mode . diff-hl-dired-mode))
  :custom
  (diff-hl-side 'right))
#+end_src

* Editing

Convert the region to lower or upper case.

#+begin_src emacs-lisp
(use-package emacs
  :config
  (put 'downcase-region 'disabled nil)
  (put 'upcase-region 'disabled nil))
#+end_src

Restrict editing in this buffer to the current region.

#+begin_src emacs-lisp
(use-package emacs
  :config
  (put 'narrow-to-region 'disabled nil))
#+end_src

Enables hungry deletion in all modes.

#+begin_src emacs-lisp
(use-package hungry-delete
  :ensure t
  :diminish hungry-delete-mode
  :custom
  (hungry-delete-join-reluctantly t)
  :hook
  (after-init . global-hungry-delete-mode))
#+end_src

Writable grep buffer and apply the changes to files.

#+begin_src emacs-lisp
(use-package wgrep
  :ensure t)
#+end_src

* Programming

Tabs are evil, use 4 spaces as default.

#+begin_src emacs-lisp
(use-package emacs
  :config
  (setq-default indent-tabs-mode nil)
  (setq-default tab-width 4))
#+end_src

Emacs client/library for the Language Server Protocol.

#+begin_src emacs-lisp
(use-package lsp-mode
  :ensure t
  :after which-key
  :commands (lsp lsp-deferred)
  :init
  (setq lsp-keymap-prefix "C-c l")
  :config
  (lsp-enable-which-key-integration t))
#+end_src

#+begin_src emacs-lisp
(use-package yaml-mode
  :ensure t
  :defer t)

(use-package cmake-mode
  :ensure t
  :defer t)

(use-package flycheck
  :ensure t
  :diminish flycheck-mode
  :hook (prog-mode . flycheck-mode))
#+end_src

Setup how compilation should behave.

#+begin_src emacs-lisp
(use-package emacs
  :config
  (setq-default compilation-ask-about-save nil)
  (setq-default compilation-always-kill t)
  (setq-default compilation-scroll-output 'first-error))
#+end_src

# Colorize compilation buffer.

# #+begin_src emacs-lisp
#   (use-package ansi-color
#     :ensure t
#     :config (add-hook 'compilation-filter-hook 'colorize-compilation-buffer))

#   (defun colorize-compilation-buffer ()
#     (ansi-color-apply-on-region compilation-filter-start (point)))
# #+end_src

Configure c/c++ indentation.

#+begin_src emacs-lisp
(use-package cc-mode
  :defer t
  :config
  (setq c-default-style "linux" c-basic-offset 2)
  (c-set-offset 'case-label '+))
#+end_src

Diminish eldoc-mode.

#+begin_src emacs-lisp
(use-package eldoc
  :diminish eldoc-mode)
#+end_src

** Python

When working with python it is usually a good idea to set up a virtual environment.

#+begin_example bash
python -m venv .venv
#+end_example

Python virtual environment interface for Emacs.

#+begin_src emacs-lisp
(use-package pyvenv
  :ensure t
  :hook (python-mode . pyvenv-mode)
  :bind
  (:map python-mode-map
        ("C-c C-a" . pyvenv-activate)))
#+end_src

Python Black for Emacs.

#+begin_src emacs-lisp
(use-package blacken
  :ensure t
  :after python
  :bind
  (:map python-mode-map
        ("C-c C-b" . blacken-buffer)))
#+end_src

* Shell/Terminal

Hide line numbers in terminals and shells.

#+begin_src emacs-lisp
(use-package shell
  :commands shell
  :config
  (add-hook 'shell-mode-hook (lambda () (display-line-numbers-mode 0))))

(use-package eshell
  :commands eshell
  :config
  (add-hook 'eshell-mode-hook (lambda () (display-line-numbers-mode 0))))

(use-package term
  :commands term
  :config
  (add-hook 'term-mode-hook (lambda () (display-line-numbers-mode 0))))
#+end_src

* Org mode

Org mode is for keeping notes, maintaining TODO lists, planning projects, and authoring documents with a fast and effective plain-text system.

#+begin_src emacs-lisp
(use-package org
  :config
  (defun org-mode-setup ()
    (display-line-numbers-mode 0)
    (visual-line-mode 1)
    (org-indent-mode))
  (setq org-ellipsis " ▾")
  (setq org-hide-emphasis-markers t)
  :hook (org-mode . org-mode-setup))
#+end_src

UTF-8 bullets for org-mode.

#+begin_src emacs-lisp
(use-package org-bullets
  :ensure t
  :after org
  :hook (org-mode . org-bullets-mode)
  :custom
  (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))
#+end_src

Configure org source code blocks.

#+begin_src emacs-lisp
(use-package org-src
  :after org
  :config
  (setq org-src-window-setup 'current-window)
  (setq org-src-fontify-natively t)
  (setq org-src-preserve-indentation t)
  (setq org-src-tab-acts-natively t))
#+end_src

* Help

Emacs package that displays available keybindings in popup.

#+begin_src emacs-lisp
(use-package which-key
  :ensure t
  :diminish which-key-mode
  :custom
  (which-key-idle-delay 0.5)
  :hook
  (after-init . which-key-mode))
#+end_src

A better Emacs *help* buffer.

#+begin_src emacs-lisp
(use-package helpful
  :ensure t
  :bind
  ([remap describe-function] . helpful-callable)
  ([remap describe-command] . helpful-command)
  ([remap describe-variable] . helpful-variable)
  ([remap describe-key] . helpful-key))
#+end_src

* Miscellaneous

Miscellaneous packages.

#+begin_src emacs-lisp
(use-package hydra
  :ensure t
  :defer t)
#+end_src

Use qutebrowser to browse.

#+begin_src emacs-lisp
(use-package emacs
  :config
  (setq browse-url-browser-function 'browse-url-generic)
  (setq browse-url-generic-program "qutebrowser"))
#+end_src

Writing 'yes/no' takes to much time...

#+begin_src emacs-lisp
(use-package emacs
  :config
  (defalias 'yes-or-no-p 'y-or-n-p)
  (setq large-file-warning-threshold nil)
  (setq vc-follow-symlinks t))
#+end_src

* Multimedia

An Emacs web feeds client.

#+begin_src emacs-lisp
(use-package elfeed
  :ensure t
  :commands elfeed
  :bind
  (:map elfeed-search-mode-map
        ("v" . elfeed-search-mpv)
        :map elfeed-show-mode-map
        ("v" . elfeed-show-mpv))
  :config
  (defun elfeed-search-mpv ()
    "Open the current entry in mpv."
    (interactive)
    (let ((entry (car (elfeed-search-selected)))
          (url (elfeed-entry-link (car (elfeed-search-selected)))))
      (elfeed-untag entry 'unread)
      (start-process "*elfeed-mpv*" nil "mpv" url)
      (elfeed-search-update-entry entry)
      (unless elfeed-search-remain-on-entry
        (forward-line))))

  (defun elfeed-show-mpv ()
    "Open the current entry in mpv."
    (interactive)
    (let ((url (elfeed-entry-link elfeed-show-entry)))
      (start-process "*elfeed-mpv*" nil "mpv" url))))
#+end_src

* Private

Load private file if it exists and is readable.

#+begin_src emacs-lisp
(use-package emacs
  :config
  (let ((private-file (expand-file-name "private.el" user-emacs-directory)))
    (if (file-readable-p private-file)
        (load-file private-file))))
#+end_src
