# shellcheck shell=bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Setup aliases
alias ls='exa --icons --group-directories-first'
alias ll='ls -la'
alias e='emacsclient -n'
alias enw='emacs --no-window-system'
alias g='git'
alias d='docker'

# Docker/Docker Compose aliases
alias dps='docker ps --format "table {{.ID}}\t{{.Image}}\\t{{.Status}}\t{{.Names}}"'
alias dup='docker compose up --detach --force-recreate'
alias dlogs='docker compose logs --follow --tail 100'
alias dclean='docker system prune --all --volumes'

# Export
export PATH="$HOME/.local/bin:$PATH"
GPG_TTY=$(tty)
export GPG_TTY

# Configure fzf
# shellcheck source=/dev/null
source /usr/share/fzf/completion.bash
# shellcheck source=/dev/null
source /usr/share/fzf/key-bindings.bash
export FZF_DEFAULT_COMMAND="ag --hidden --follow --ignore .git --filename-pattern ''"
export FZF_DEFAULT_OPTS="--height 25% --border sharp --no-scrollbar --layout reverse --cycle"
_fzf_setup_completion path e enw

# Configure prompt
eval "$(starship init bash)"

# Enable git completion
# shellcheck source=/dev/null
source /usr/local/share/bash-completion/completions/git

# Active direnv
eval "$(direnv hook bash)"
export DIRENV_LOG_FORMAT=""

# Setup zoxide
eval "$(zoxide init --cmd cd bash)"

# Setup atuin
eval "$(atuin init bash --disable-up-arrow --disable-ctrl-r)"

# Load local bashrc if it exists
if [ -e $HOME/.bashrc.local ]; then
  source $HOME/.bashrc.local
fi
