format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$python\
$cmd_duration\
$line_break\
$character"""

right_format = ''
continuation_prompt = '[∙](bright-black) '
scan_timeout = 30
command_timeout = 500
add_newline = false

[character]
format = '$symbol '
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold green)'
vimcmd_visual_symbol = '[❮](bold yellow)'
vimcmd_replace_symbol = '[❮](bold purple)'
vimcmd_replace_one_symbol = '[❮](bold purple)'
disabled = false

[cmd_duration]
min_time = 2000
format = 'took [$duration]($style) '
style = 'yellow bold'
show_milliseconds = false
disabled = false
show_notifications = false
min_time_to_notify = 45000

[directory]
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 0
use_logical_path = true
format = '[$path]($style)[$read_only]($read_only_style) '
repo_root_format = '[$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
style = 'cyan bold'
disabled = false
read_only = ' 󰌾'
read_only_style = 'red'
truncation_symbol = ''
home_symbol = '~'
use_os_path_sep = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ' '
style = 'bold purple'
truncation_length = 9223372036854775807
truncation_symbol = '…'
only_attached = false
always_show_remote = false
ignore_branches = []
disabled = false

[git_commit]
commit_hash_length = 7
format = '[\($hash$tag\)]($style) '
style = 'green bold'
only_detached = true
disabled = false
tag_symbol = ' 🏷  '
tag_disabled = true
tag_max_candidates = 0

[git_state]
rebase = 'REBASING'
merge = 'MERGING'
revert = 'REVERTING'
cherry_pick = 'CHERRY-PICKING'
bisect = 'BISECTING'
am = 'AM'
am_or_rebase = 'AM/REBASE'
style = 'bold yellow'
format = '\([$state( $progress_current/$progress_total)]($style)\) '
disabled = false

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = 'red bold'
stashed = ''
ahead = '⇡'
behind = '⇣'
up_to_date = ''
diverged = '⇕'
conflicted = '='
deleted = '✘'
renamed = '»'
modified = '!'
staged = '+'
untracked = '?'
ignore_submodules = false
disabled = false

[line_break]
disabled = false

[python]
format = '[(\[${symbol}$virtualenv\] )]($style)'
style = 'yellow bold'
symbol = ' '
disabled = false
