" Files
set encoding=utf8
set ffs=unix,dos,mac
filetype plugin on
filetype indent on

" Prettify
set number
set relativenumber
set cursorline
set ruler
set showmatch
syntax enable
colorscheme industry

" Searching
set ignorecase
set smartcase
set hlsearch
set incsearch

" Tabs
set shiftwidth=4
set tabstop=4
set smarttab
set expandtab

" Quiet
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" No backups
set nobackup
set nowb
set noswapfile
