---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: latest

- name: Add to group
  become: true
  ansible.builtin.user:
    name: claes
    groups: docker
    append: true
  when: false

- name: Enable and start service
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ docker_services }}"
  when: ansible_facts.virtualization_type != "docker"
