---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: latest
  when: can_become

- name: Enable and start service
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ docker_services }}"
  when: ansible_facts.virtualization_type != "docker" and can_become
