---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: latest
  when: ansible_facts.os_family == "Archlinux" and can_become

- name: Install docker
  ansible.builtin.include_role:
    name: geerlingguy.docker
  when: ansible_facts.os_family == "Debian" and can_become and ansible_facts.virtualization_type != "docker"  # yamllint disable-line rule:line-length

- name: Enable and start service
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ docker_services }}"
  when: ansible_facts.virtualization_type != "docker" and can_become
