---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ docker_packages }}"

- name: Enable and start service
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ docker_services }}"

- name: Add to group
  become: true
  ansible.builtin.user:
    name: claes
    groups: docker
    append: true
  when: false
