---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ starship_packages }}"

- name: Link config files
  ansible.builtin.include_role:
    name: link_config
  vars:
    config_files: "{{ starship_config_files}}"
