---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ alacritty_packages }}"
    state: latest
  when: ansible_facts.os_family == "Archlinux" and can_become

- name: Add config
  ansible.builtin.include_role:
    name: add_config
  vars:
    add_config_files: "{{ alacritty_config_files }}"
