---
- name: Install package
  become: true
  ansible.builtin.package:
    name: "{{ alacritty_packages }}"
    state: latest
  when: ansible_facts.os_family == "Archlinux"

- name: Link config files
  ansible.builtin.include_role:
    name: link_config
  vars:
    link_config_files: "{{ alacritty_config_files }}"
