---
- name: Create directory
  become: false
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ mimeapps_config_dir }}"

- name: Create link
  become: false
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ mimeapps_config_dir }}/{{ item }}"
    state: link
  loop: "{{ mimeapps_config_files }}"
