---
name: Run pre-commit hooks

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.x
      - run: pip install virtualenv==v20.24.5  # temp fix for gitlint
      - uses: pre-commit/action@v3.0.1
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --hook-stage manual gitlint-ci
