---
name: Run pre-commit hooks

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          ref: main
      - uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.0
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --hook-stage manual gitlint-ci
